
services:

  postgres:
    image: postgres:latest
    container_name: web_electronics_postgres
    restart: unless-stopped
    ports:
      - "5000:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web_electronics_db
      PGDATA: /var/lib/data/postgresql

  redis:
    image: redis:latest
    container_name: web_electronics_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/data/redis

  web-electronics:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/web_electronics_db

volumes:
  redis_data: