
services:

  postgres:
    image: postgres:latest
    container_name: web_electronics_postgres
    restart: unless-stopped
    ports:
      - "5000:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web_electronics_db
      PGDATA: /var/lib/data/postgresql