


### Security Requests



###
GET /api/v1/security/csrf-token
Host: localhost:9000
Accept: application/json



### Identity Requests



###
GET /api/v1/identities
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
GET /api/v1/identities/by-id?identityId=c13c7100-5249-46a5-a9e8-91160806377c
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
POST /api/v1/identities/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
X-Csrf-Token: ML00SD2gU9dgnlfH_DUgwXbLDKMwUXiowm-JKe9kIePy794lB4UBKlmQZbJNqG7zzRgU90b4IZoBM0iFoQu6HtZVFYCQju0S

{
    "authority": "ADMIN",
    "email": "burgasvv@gmail.com",
    "pass": "burgasvv",
    "firstname": "Бургас",
    "lastname": "Вячеслав",
    "patronymic": "Васильевич"
}

###
PUT /api/v1/identities/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgvv@gmail.com burgasvv
X-Csrf-Token: 9TjNI3preR2VDY8i48s3LzzlN-dN6-Ot44UEVnQTxLKF1p0izAn8FEpTGHm4b-5EguYDHVqGGt5_3YeAh7I3NUIhp9O2sqlH

{
    "id": "68e4b3d5-0475-4c57-9d75-062c864e2828",
    "email": "burgasvv@gmail.com"
}

###
DELETE /api/v1/identities/delete?identityId=282d47a3-fa06-423f-8964-7b07a27a01db
Host: localhost:9000
Accept: application/json

###
PUT /api/v1/identities/change-password?identityId=282d47a3-fa06-423f-8964-7b07a27a01db&newPassword=burgasvv
Host: localhost:9000
Accept: application/json

###
PUT /api/v1/identities/enable-disable?identityId=282d47a3-fa06-423f-8964-7b07a27a01db&enabled=true
Host: localhost:9000
Accept: application/json



### Store Requests



###
GET /api/v1/stores
Host: localhost:9000
Accept: application/json

###
GET /api/v1/stores/by-id?storeId=816954cf-0d9e-443c-8de0-1bdd2c53678a
Host: localhost:9000
Accept: application/json

###
POST /api/v1/stores/create-update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: 8EJ4uSjZPm2SPKRQ0oaPYbo6gpO8rrA_KVzl1DLx6lO06GoClXFPjU3pDQi_XpVo5Ku7VdxYr6qEyocSEG7ctQGU32vQ2l81

{
    "address": {
        "city": "Новосибирск",
        "street": "ул. Морская",
        "house": "25/1",
        "apartment": "154a"
    }
}

###
DELETE /api/v1/stores/delete?storeId=dd0809ea-8ee1-41cf-b4ca-3fe4571aebf9
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: xKHRL-Ocaj4tGVtUOopma_s1TpFEKXMkQXyHwQ7cC5Vavs7N9MSySdv5DwsAKzkwCKdSCcIEY6h8TUQJdBqz8T7vPvRtjvb-



### Category Requests



###
GET /api/v1/categories
Host: localhost:9000
Accept: application/json

###
GET /api/v1/categories/by-id?categoryId=8f8f859d-b833-4dba-b006-b916b4bdf329
Host: localhost:9000
Accept: application/json

###
POST /api/v1/categories/create-update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: bd5llQb2P0HS_mts92hTSue6vQRusIay_MVP9QYHLjiDBTnhCOlc92CSCXH_nVJZk0VnKN-NkGZZgrCfzaR9x2BhHQ7gMQ-D

{
    "name": "Наушники",
    "description": "Описание категории Наушники"
}

###
DELETE /api/v1/categories/delete?categoryId=da92210c-5c4b-45e9-9ac9-23018a58d9cc
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: bd5llQb2P0HS_mts92hTSue6vQRusIay_MVP9QYHLjiDBTnhCOlc92CSCXH_nVJZk0VnKN-NkGZZgrCfzaR9x2BhHQ7gMQ-D



### ProductRequests



###
GET /api/v1/products
Host: localhost:9000
Accept: application/json

###
GET /api/v1/products/by-id?productId=51c12db4-be8e-4d73-bb17-4093ac77427c
Host: localhost:9000
Accept: application/json

###
POST /api/v1/products/create-update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: 8EJ4uSjZPm2SPKRQ0oaPYbo6gpO8rrA_KVzl1DLx6lO06GoClXFPjU3pDQi_XpVo5Ku7VdxYr6qEyocSEG7ctQGU32vQ2l81

{
    "name": "NZ-350",
    "categoryId": "8f8f859d-b833-4dba-b006-b916b4bdf329",
    "description": "Описание модели смартфона NZ-350",
    "price": 85900.0
}



### Store Product Requests



###
POST /api/v1/store-product/add
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: sUcA4mekg-aN1RtFncpJgiexis6euNyn8YulUEVbr-MlJfGQ1HQ31gKUsIOgtyp9q-d9tkHTp_em3OuKyLmcMXY-mttBF8Sn

{
    "storeId": "816954cf-0d9e-443c-8de0-1bdd2c53678a",
    "productId": "51c12db4-be8e-4d73-bb17-4093ac77427c",
    "amount": 60
}



### Bucket Requests



###
GET /api/v1/buckets/by-id?bucketId=03bb1a64-8e9f-47c4-970d-211707e44a7a
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
POST /api/v1/buckets/add-product
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: -e3oy0m6aaKZE7lbDPMv-VLARyQBqYDKAt59fZexmSeayik2wNSL_3-PC5e0IYtsOd4bz2CmakVlyLPnOrtISKTVqRar-RoB

{
    "bucketId": "03bb1a64-8e9f-47c4-970d-211707e44a7a",
    "productId": "51c12db4-be8e-4d73-bb17-4093ac77427c",
    "amount": 1
}

###
DELETE /api/v1/buckets/remove-product
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: -e3oy0m6aaKZE7lbDPMv-VLARyQBqYDKAt59fZexmSeayik2wNSL_3-PC5e0IYtsOd4bz2CmakVlyLPnOrtISKTVqRar-RoB

{
    "bucketId": "03bb1a64-8e9f-47c4-970d-211707e44a7a",
    "productId": "51c12db4-be8e-4d73-bb17-4093ac77427c"
}

###
DELETE /api/v1/buckets/remove-all-products?bucketId=03bb1a64-8e9f-47c4-970d-211707e44a7a
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: -e3oy0m6aaKZE7lbDPMv-VLARyQBqYDKAt59fZexmSeayik2wNSL_3-PC5e0IYtsOd4bz2CmakVlyLPnOrtISKTVqRar-RoB

###
POST /api/v1/buckets/increase-product
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: -e3oy0m6aaKZE7lbDPMv-VLARyQBqYDKAt59fZexmSeayik2wNSL_3-PC5e0IYtsOd4bz2CmakVlyLPnOrtISKTVqRar-RoB

{
    "bucketId": "03bb1a64-8e9f-47c4-970d-211707e44a7a",
    "productId": "51c12db4-be8e-4d73-bb17-4093ac77427c"
}

###
POST /api/v1/buckets/decrease-product
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: -e3oy0m6aaKZE7lbDPMv-VLARyQBqYDKAt59fZexmSeayik2wNSL_3-PC5e0IYtsOd4bz2CmakVlyLPnOrtISKTVqRar-RoB

{
    "bucketId": "03bb1a64-8e9f-47c4-970d-211707e44a7a",
    "productId": "51c12db4-be8e-4d73-bb17-4093ac77427c"
}