


### Security Requests



###
GET /api/v1/security/csrf-token
Host: localhost:9000
Accept: application/json



### Identity Requests



###
GET /api/v1/identities
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
GET /api/v1/identities/by-id?identityId=68e4b3d5-0475-4c57-9d75-062c864e2828
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
POST /api/v1/identities/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
X-Csrf-Token: e2vn6Q0lAG_DhaZ4z6DcAOUhzwRzvzXSJV8tSPfDQ_5U68DDQlrW3j0dYQvu58cero3oMoNC4j1BiVH_QWgeK8HxIJ9nj_Sm

{
    "authority": "ADMIN",
    "email": "burgvv@gmail.com",
    "pass": "burgasvv",
    "firstname": "Бургас",
    "lastname": "Вячеслав",
    "patronymic": "Васильевич"
}

###
PUT /api/v1/identities/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgvv@gmail.com burgasvv
X-Csrf-Token: 9TjNI3preR2VDY8i48s3LzzlN-dN6-Ot44UEVnQTxLKF1p0izAn8FEpTGHm4b-5EguYDHVqGGt5_3YeAh7I3NUIhp9O2sqlH

{
    "id": "68e4b3d5-0475-4c57-9d75-062c864e2828",
    "email": "burgasvv@gmail.com"
}

###
DELETE /api/v1/identities/delete?identityId=282d47a3-fa06-423f-8964-7b07a27a01db
Host: localhost:9000
Accept: application/json

###
PUT /api/v1/identities/change-password?identityId=282d47a3-fa06-423f-8964-7b07a27a01db&newPassword=burgasvv
Host: localhost:9000
Accept: application/json

###
PUT /api/v1/identities/enable-disable?identityId=282d47a3-fa06-423f-8964-7b07a27a01db&enabled=true
Host: localhost:9000
Accept: application/json



### Store Requests



###
GET /api/v1/stores
Host: localhost:9000
Accept: application/json

###
GET /api/v1/stores/by-id?storeId=96491fed-3743-4978-a75d-10d9b6c08cf5
Host: localhost:9000
Accept: application/json

###
POST /api/v1/stores/create-update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: 77v5SqtJx-oOtisIszEk-ZwswG6RNrvGZOZBLwcCR7l4p-hfioLILJMr8dgjjxhphBwQz_kd7QyhBo_rB4AiTDBjcd0elYlv

{
    "address": {
        "city": "Новосибирск",
        "street": "ул. Морская",
        "house": "25/1",
        "apartment": "154a"
    }
}

###
DELETE /api/v1/stores/delete?storeId=dd0809ea-8ee1-41cf-b4ca-3fe4571aebf9
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: xKHRL-Ocaj4tGVtUOopma_s1TpFEKXMkQXyHwQ7cC5Vavs7N9MSySdv5DwsAKzkwCKdSCcIEY6h8TUQJdBqz8T7vPvRtjvb-



### Category Requests



###
GET /api/v1/categories
Host: localhost:9000
Accept: application/json

###
GET /api/v1/categories/by-id?categoryId=5da6aa00-0954-4c60-a14b-dac4ed0404c6
Host: localhost:9000
Accept: application/json

###
POST /api/v1/categories/create-update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: bd5llQb2P0HS_mts92hTSue6vQRusIay_MVP9QYHLjiDBTnhCOlc92CSCXH_nVJZk0VnKN-NkGZZgrCfzaR9x2BhHQ7gMQ-D

{
    "name": "Наушники",
    "description": "Описание категории Наушники"
}

###
DELETE /api/v1/categories/delete?categoryId=da92210c-5c4b-45e9-9ac9-23018a58d9cc
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: bd5llQb2P0HS_mts92hTSue6vQRusIay_MVP9QYHLjiDBTnhCOlc92CSCXH_nVJZk0VnKN-NkGZZgrCfzaR9x2BhHQ7gMQ-D



### ProductRequests



###
GET /api/v1/products
Host: localhost:9000
Accept: application/json

###
GET /api/v1/products/by-id?productId=fc83d5df-33d5-49e8-86d0-331575b815a5
Host: localhost:9000
Accept: application/json

###
POST /api/v1/products/create-update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: lk6Tciq6gbYiC-nxQ0Gy8hfCBekgIxImbMnt2caY1FUQj--kp373QRmNttUPad_FJWyGynOmKNAXRnYLVKva7ff7smJy7tic

{
    "name": "M54-320",
    "categoryId": "5da6aa00-0954-4c60-a14b-dac4ed0404c6",
    "description": "Описание модели смартфона M54-320",
    "price": 120340.50
}



### Store Product Requests



###
POST /api/v1/store-product/add
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: gZGBTb3NGfjx7fJajVP5s0AzsLP7tO6dVbU8X_boYEmDF5cc5KiwK4WvL8rc1ME7un7NhSUCndHLhNqwNtNfPMGJVi3lJfYs

{
    "storeId": "96491fed-3743-4978-a75d-10d9b6c08cf5",
    "productId": "fc83d5df-33d5-49e8-86d0-331575b815a5",
    "amount": 500
}